version: '3.4'

services:
  changeStream:
    image: ${DOCKER_REGISTRY-}changestream
    build:
      context: ./src
      dockerfile: ./ChangeStream/Dockerfile
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 1

  pdm:
    image: ${DOCKER_REGISTRY-}pdm
    build:
      context: ./src
      dockerfile: ./pdm/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - changeStream
    deploy:
      mode: replicated
      replicas: 1
networks:
  default:
    external:
      name: ${NETWORK}